# Generated by Django 4.1.4 on 2022-12-07 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Term', models.TextField()),
                ('Year', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Instructor', models.TextField()),
                ('Classroom', models.TextField()),
                ('ClassTime', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.TextField()),
                ('CourseDesc', models.TextField()),
                ('Credits', models.BigIntegerField()),
                ('DeptID', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GradeValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QGrade', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastName', models.TextField()),
                ('FirstName', models.TextField()),
                ('MiddleName', models.TextField()),
                ('Addr1', models.TextField()),
                ('Addr2', models.TextField()),
                ('City', models.TextField()),
                ('StateProvince', models.TextField()),
                ('Country', models.TextField()),
                ('PostalCode', models.TextField()),
                ('Email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='stuclasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.classes')),
                ('Grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.gradevalues')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.students')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='CourseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hello.courses'),
        ),
    ]
